AllCops:
  NewCops: enable
Layout/LineLength:
  Enabled: false
Style/GlobalVars:
  AllowedVariables:
    - $metadata
    - $images
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
